offset:
  arm_joint_1: 0
  arm_joint_2: 0
  arm_joint_3: 0
  arm_joint_4: 0
  gripper_servo_joint: 0
init_pose_for_offset_tuner:
  arm_joint_1: 0
  arm_joint_2: 0
  arm_joint_3: 0
  arm_joint_4: 0
  gripper_servo_joint: 0
